### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by gudovskiy** [dongyp13/Stochastic-Quantization#1]
@dongyp13 Hi, thanks for sharing code. Could you release your pretrained models (specifically ImageNet AlexNet/ResNet SQ-TWN)? I try to reproduce your results but accuracy is very low even at first iterations...

**Comment by dongyp13** [comment]
Hi, it's true that the accuracy is very low at first iterations (even at the first three quantization stages), but it will finally converge at the last stage with r = 100%. I will release the pretrain models after a few days.

**Comment by dongyp13** [comment]
Hi @gudovskiy, our models are trained on another version of codes, which are not compatible with those on GitHub. We remove some functions and APIs in the GitHub version to make them clearer. You can try to train the model yourself from scratch. If you have some problems of training, you can email me to ask for the original version of codes and models.
