### ISSUE TITLE
input与bias的量化

### ISSUE THREAD

**Issue by vicwer** [dongyp13/Stochastic-Quantization#3]
Hi, 您好：
        看了您的论文以及源码，获益颇多，在此有几个问题想请教一下，还请帮忙解惑~
        1. 权重量化为低比特，input 以及features map是float32，是否有什么方法也可以做到量化？我想过直接映射到8bit，但是与-1这样的权重乘积会出错，除非把权重量化到8bit，然后扩成16bit计算，防止溢出，效率会下降，而且每层还需要取max和min。
        2. bias，batchnorm，prelu这些一个参数作用于整个feature map，量化的话，是否会有很大损失？

**Comment by dongyp13** [comment]
您好，感谢您对我们的工作的关注。我们最近也在尝试activation低比特的方法，之前的一些工作也有尝试过（例如dorefa）。对于第二个问题我们没有考虑这些整体参数对结果的影响，如果您有兴趣可以深入研究一下。

祝好！
董胤蓬

**Comment by vicwer** [comment]
ok, thx~
