### ISSUE TITLE
Quantize the first and last layers

### ISSUE THREAD

**Issue by sicnarf1a** [dongyp13/Stochastic-Quantization#4]
@dongyp13 Hi, I read your paper and thanks for sharing code.
I am now trying to reproduce your paper with tensorflow. Since I do not know anything about caffe, so I just need to reproduce it with the information only on paper.

My question is,
1) did you quantize the first and last layers of the network?
2) and I wonder if you got the results by ensemble method.
3) Finally, as an example of the first stage, I wonder whether 50% stochastic sampling was performed in the entire layer or 50% sampling was performed in each layer.

Again, thanks for sharing the code and congratulations on your acceptance at the BMVC conference.
Best Regards.

**Comment by dongyp13** [comment]
@sicnarf1a Thanks for your interest. For your questions:
1. We did quantize the weights in the first and last layer.
2. We do not use any ensemble methods for models or data.
3. We perform stochastic sampling in each layer with filters as the basic elements. For example, if a layer has 64 output channels (filters), 50% quantization means 32 channels are quantized.

Hope it be useful.

**Comment by sicnarf1a** [comment]
@dongyp13 Thank you very much for your kind reply! It has been a great help.
Thanks again.
