### ISSUE TITLE
BWN反传梯度更新

### ISSUE THREAD

**Issue by zzqiuzz** [dongyp13/Stochastic-Quantization#5]
Wow.很棒的工作！
我现在是仿照您的工作自己实现了下BWN,我浏览下了您的代码，貌似在梯度更新的时候并没有按照paper里推导公式来更新的 是直接将算出的梯度更新到原来的权重里的，或者代码是在其它的地方实现了这一更新吗
https://github.com/dongyp13/Stochastic-Quantization/blob/fa384c12e8b6e957190e56f063dade62b087c9d5/caffe/src/caffe/layers/inner_product_layer_binary.cu#L144

**Comment by dongyp13** [comment]
是的，直接把对binary weight的梯度用于更新了。
